using EloBuddy;

namespace AiBuddy.Utils.DamageLib
{
    class GetDamageType
    {
        /// <summary>
        /// Gets the damagetype for each champ.
        /// </summary>
        
        /// <returns>
        /// DamageType.[Champ's main damagetype]
        /// </returns>
        
        public static DamageType Get()
        {
            switch (ObjectManager.Player.ChampionName)
            {
                case "Aatrox":
                    return DamageType.Physical;
                case "Ahri":
                    return DamageType.Magical;
                case "Akali":
                    return DamageType.Magical;
                case "Alistar":
                    return DamageType.Magical;
                case "Amumu":
                    return DamageType.Magical;
                case "Anivia":
                    return DamageType.Magical;
                case "Annie":
                    return DamageType.Magical;
                case "Ashe":
                    return DamageType.Physical;
                case "Azir":
                    return DamageType.Magical;
                case "Bard":
                    return DamageType.Magical;
                case "Blitzcrank":
                    return DamageType.Magical;
                case "Brand":
                    return DamageType.Magical;
                case "Braum":
                    return DamageType.Magical;
                case "Caitlyn":
                    return DamageType.Physical;
                case "Cassiopeia":
                    return DamageType.Magical;
                case "ChoGath":
                    return DamageType.Magical;
                case "Corki":
                    return DamageType.Physical;
                case "Darius":
                    return DamageType.Physical;
                case "Diana":
                    return DamageType.Magical;
                case "DrMundo":
                    return DamageType.Mixed;
                case "Draven":
                    return DamageType.Physical;
                case "Ekko":
                    return DamageType.Magical;
                case "Elise":
                    return DamageType.Magical;
                case "Evelynn":
                    return DamageType.Mixed;
                case "Ezreal":
                    return DamageType.Physical;
                case "Fiddlesticks":
                    return DamageType.Magical;
                case "Fiora":
                    return DamageType.Physical;
                case "Fizz":
                    return DamageType.Magical;
                case "Galio":
                    return DamageType.Magical;
                case "Gangplank":
                    return DamageType.Physical;
                case "Garen":
                    return DamageType.Physical;
                case "Gnar":
                    return DamageType.Physical;
                case "Gragas":
                    return DamageType.Magical;
                case "Graves":
                    return DamageType.Physical;
                case "Hecarim":
                    return DamageType.Physical;
                case "Heimerdinger":
                    return DamageType.Magical;
                case "Irelia":
                    return DamageType.Physical;
                case "Janna":
                    return DamageType.Physical;
                case "Jarvan IV":
                    return DamageType.Physical;
                case "Jax":
                    return DamageType.Mixed;
                case "Jayce":
                    return DamageType.Physical;
                case "Jinx":
                    return DamageType.Physical;
                case "Kalista":
                    return DamageType.Physical;
                case "Karma":
                    return DamageType.Magical;
                case "Kassadin":
                    return DamageType.Magical;
                case "Katarina":
                    return DamageType.Magical;
                case "Kayle":
                    return DamageType.Mixed;
                case "Kennen":
                    return DamageType.Magical;
                case "KhaZix":
                    return DamageType.Physical;
                case "KogMaw":
                    return DamageType.Physical;
                case "LeBlanc":
                    return DamageType.Magical;
                case "LeeSin":
                    return DamageType.Physical;
                case "Leona":
                    return DamageType.Mixed;
                case "Lissandra":
                    return DamageType.Magical;
                case "Lucian":
                    return DamageType.Physical;
                case "Lulu":
                    return DamageType.Magical;
                case "Lux":
                    return DamageType.Magical;
                case "Malphite":
                    return DamageType.Magical;
                case "Malzahar":
                    return DamageType.Magical;
                case "Maokai":
                    return DamageType.Magical;
                case "MasterYi":
                    return DamageType.Physical;
                case "MissFortune":
                    return DamageType.Physical;
                case "Mordekaiser":
                    return DamageType.Magical;
                case "Morgana":
                    return DamageType.Magical;
                case "Nami":
                    return DamageType.Magical;
                case "Nasus":
                    return DamageType.Physical;
                case "Nautilus":
                    return DamageType.Mixed;
                case "Nidalee":
                    return DamageType.Magical;
                case "Nocturne":
                    return DamageType.Physical;
                case "Nunu":
                    return DamageType.Magical;
                case "Olaf":
                    return DamageType.Physical;
                case "Orianna":
                    return DamageType.Magical;
                case "Pantheon":
                    return DamageType.Physical;
                case "Poppy":
                    return DamageType.Mixed;
                case "Quinn":
                    return DamageType.Physical;
                case "Rammus":
                    return DamageType.Mixed;
                case "RekSai":
                    return DamageType.Physical;
                case "Renekton":
                    return DamageType.Physical;
                case "Rengar":
                    return DamageType.Physical;
                case "Riven":
                    return DamageType.Physical;
                case "Rumble":
                    return DamageType.Magical;
                case "Ryze":
                    return DamageType.Magical;
                case "Sejuani":
                    return DamageType.Mixed;
                case "Shaco":
                    return DamageType.Physical;
                case "Shen":
                    return DamageType.Mixed;
                case "Shyvana":
                    return DamageType.Physical;
                case "Singed":
                    return DamageType.Magical;
                case "Sion":
                    return DamageType.Physical;
                case "Sivir":
                    return DamageType.Physical;
                case "Skarner":
                    return DamageType.Physical;
                case "Sona":
                    return DamageType.Magical;
                case "Soraka":
                    return DamageType.Magical;
                case "Swain":
                    return DamageType.Magical;
                case "Syndra":
                    return DamageType.Magical;
                case "TahmKench":
                    return DamageType.Mixed;
                case "Talon":
                    return DamageType.Physical;
                case "Taric":
                    return DamageType.Magical;
                case "Teemo":
                    return DamageType.Magical;
                case "Thresh":
                    return DamageType.Magical;
                case "Tristana":
                    return DamageType.Physical;
                case "Trundle":
                    return DamageType.Physical;
                case "Tryndamere":
                    return DamageType.Physical;
                case "Twisted Fate":
                    return DamageType.Magical;
                case "Twitch":
                    return DamageType.Physical;
                case "Udyr":
                    return DamageType.Mixed;
                case "Urgot":
                    return DamageType.Physical;
                case "Varus":
                    return DamageType.Physical;
                case "Vayne":
                    return DamageType.Physical;
                case "Veigar":
                    return DamageType.Magical;
                case "VelKoz":
                    return DamageType.Magical;
                case "Vi":
                    return DamageType.Physical;
                case "Viktor":
                    return DamageType.Magical;
                case "Vladimir":
                    return DamageType.Magical;
                case "Volibear":
                    return DamageType.Mixed;
                case "Warwick":
                    return DamageType.Physical;
                case "Wukong":
                    return DamageType.Physical;
                case "Xerath":
                    return DamageType.Magical;
                case "XinZhao":
                    return DamageType.Physical;
                case "Yasuo":
                    return DamageType.Physical;
                case "Yorick":
                    return DamageType.Mixed;
                case "Zac":
                    return DamageType.Mixed;
                case "Zed":
                    return DamageType.Physical;
                case "Ziggs":
                    return DamageType.Magical;
                case "Zilean":
                    return DamageType.Magical;
                case "Zyra":
                    return DamageType.Magical;
            }
            return DamageType.Mixed;
        }
    }
}
